opencompl/Quidditch

.gitmodules, runtime/CMakeLists.txt, runtime/samples/CMakeLists.txt, runtime/snitch_cluster/CMakeLists.txt, runtime/snitch_cluster/rtl/memory.ld, runtime/snitch_cluster/rtl/src/snitch_cluster_start.S, runtime/snitch_cluster/rtl/src/snitch_cluster_start.c, runtime/snitch_cluster/rtl/src/snrt.c, runtime/snitch_cluster/rtl/src/snrt.h, runtime/snitch_cluster/rtl/src/syscalls.c, runtime/tests/CMakeLists.txt, runtime/tests/main.c
Building the snitch runtime as part of the monobuild ensures that we always use the same compiler, compilation flags and also gives us greater flexibility in assembling the parts from the snitch runtime that we need. In particular, changing the startup file to differently use the L1 of the compute cores will likely be required. Lastly, this makes it very easy to change the hardware config as it only requires changing the path to a hjson file within the cmake.
It is now possible to build and run a hello world as a check.
=> [runtime] Integrate snitch runtime into the quidditch runtime

.github/workflows/build.yaml, codegen/compiler/src/Quidditch/HoistHALOpsToFunc.cpp, runtime/cmake/quidditch_module.cmake, runtime/runtime/src/Quidditch/CMakeLists.txt, runtime/runtime/src/Quidditch/device.c, runtime/runtime/src/Quidditch/device.h, runtime/runtime/src/Quidditch/event.c, runtime/runtime/src/Quidditch/event.h, runtime/runtime/src/Quidditch/semaphore.c, runtime/runtime/src/Quidditch/semaphore.h, runtime/samples/CMakeLists.txt, runtime/samples/main.c, runtime/samples/simple_add.mlir, runtime/tests/CMakeLists.txt
This PR implements a basic sample running an xDSL generated kernel in a snitch cluster. The code currently has to be executed by a compute core (as the kernels are executed by the same caller core) and the memory allocated in L1 as that is required by streaming registers. The quidditch device was reverted to just be a fork of the `local-sync` device as the current plan is to leverage parallelism inside one cluster within a kernel for now.
=> [runtime] Add basic xDSL kernel compilation example

.github/workflows/build.yaml, .gitmodules, CMakeLists.txt, README.md, codegen/tests/CMakeLists.txt, runtime/snitch_cluster/CMakeLists.txt
The megabuild is a single top-level cmake file performing most of the required steps to build and test the entire project. Not only does this simplify CI but also serves as a good getting started point for pure users
=> [build] Add convenient megabuild

runtime/cmake/quidditch_module.cmake
If the build script detects that `iree-compile` is part of a cmake build it will now keep also trigger the other cmake build to never use an out of date `iree-compile` executable.
This should avoid some embarassing mistakes I've made in the past.
=> [runtime] Detect and keep `iree-compile` up to date

.github/workflows/build.yaml, runtime/CMakeLists.txt, runtime/toolchain/Dockerfile
None of our development setups have any size constraints on code as they're currently all in DRAM.
A faster executable greatly reduces time spent in simulation however, making this a worthwhile optimization for development.
This reduced verilator runtime by almost 3x on my local machine.
=> [toolchain] Optimize for speed rather than size

CMakeLists.txt, codegen/CMakeLists.txt, runtime/CMakeLists.txt
Using these automatically makes `cmake` convert paths given on the command line via `-D` from relative to absolute paths.
=> [cmake] use `PATH` and `FILEPATH` cache variables

runtime/requirements.txt, runtime/tests/CMakeLists.txt, runtime/util/snitch_trace_to_perfetto.py
The script analyzes the traces of each RISC-V core using ETH's script to first denote sections and get performance data about each section. Afterwards, it creates a trace file suitable for https://ui.perfetto.dev/ to create a timeline view of the kernel execution.
=> [cmake] add script for automatic performance evaluation after runs

runtime/runtime/src/Quidditch/dispatch/dispatch.c, runtime/runtime/src/Quidditch/dispatch/dispatch.h, runtime/runtime/src/Quidditch/executable/executable.c
The `wfi` instruction, technically speaking, is not guaranteed to halt the core nor be woken up by exactly the interrupt we want. Hardware barriers are the more canonical way of implementing synchronization within a cluster and our new implementation also parks the DMA core during kernel execution instead of making it busy loop. This is mainly useful for simulation time and power usage in real code.
=> [dispatch] Synchronize using barriers rather than local interrupts

runtime/runtime/src/Quidditch/executable/executable.c, runtime/util/snitch_trace_to_perfetto.py
This way we'll be able to measure time spent in between kernels within IREE machinery.
=> [runtime] trace DMA/VM core time as well

codegen/CMakeLists.txt, codegen/compiler/src/Quidditch/CMakeLists.txt, codegen/compiler/src/Quidditch/HoistHALOpsToFunc.cpp, codegen/tests/CMakeLists.txt, codegen/tests/HostHALOpsToFunc/test.mlir, codegen/tools/CMakeLists.txt, codegen/tools/quidditch-opt.cpp
The hoisting process performs cloning of the operation and relies on all operands being cloned. If we perform the replacement prior to the cloning then the operands of operations that will be cloned are remapped too early and create an invalid use of an SSA value in another function.
=> [compiler][HoistHALOps] Perform value replacement after hoisting

codegen/compiler/src/Quidditch/QuidditchTarget.cpp, runtime/cmake/quidditch_module.cmake, runtime/samples/nsnet2/main.c, runtime/samples/vec_multiply/main.c
Having both Quidditch and LLVM output allows us to freely use kernels generated by either of the two, depending on the order they're registered in our loader.
The main use-case is for us to be able to gradually introduce xDSL output by falling back to LLVM when xDSL is incapable of compiling a kernel.
=> [compiler][runtime] Compile modules with both LLVM and Quidditch

codegen/compiler/src/Quidditch/CMakeLists.txt, codegen/compiler/src/Quidditch/ConvertToRISCV.cpp, codegen/compiler/src/Quidditch/Passes.td, codegen/compiler/src/Quidditch/QuidditchTarget.cpp
This moves the conversion into the translation pipeline rather than during serialization. Our use-case for this is that we want to perform actions in the linker pass pipeline run afterward based on the output of the xDSL conversion. It additionally makes the code more readable by moving logic out of the not small QuidditchTarget.cpp file.
=> [compiler][NFC] Move `xDSL` conversion to RISC-V into a pass

codegen/compiler/src/Quidditch/CMakeLists.txt, codegen/compiler/src/Quidditch/ConvertToRISCV.cpp, codegen/compiler/src/Quidditch/DisableQuidditchVariant.cpp, codegen/compiler/src/Quidditch/HoistHALOpsToFunc.cpp, codegen/compiler/src/Quidditch/LinkExecutables.cpp, codegen/compiler/src/Quidditch/Passes.td, codegen/compiler/src/Quidditch/QuidditchTarget.cpp, runtime/cmake/quidditch_module.cmake, runtime/samples/nsnet2/CMakeLists.txt, runtime/samples/nsnet2/main.c, runtime/samples/vec_multiply/CMakeLists.txt, runtime/samples/vec_multiply/main.c
The following things happen after this PR if a kernel fails to compile with xDSL:
* The code is replaced with the same kernel compiled with LLVM
* A warning is emitted with the `stderr` output of `xdsl-opt`
* The dispatch code for Quidditch is disabled. This is required to make sure that we use the right workgroup sizes
The positive of this change is that we can now gradually introduce and fix xDSL kernels one-at-a-time for whichever NNs we are interested in.
=> [compiler] Implement fallback compilation of Quidditch kernels with LLVM

CMakeLists.txt
The build would by default not always invoke the build command of the subdirectories, even if the file changed, making it very difficult to use for incremental builds
=> [cmake] allow megabuild for incremental builds

codegen/compiler/src/Quidditch/ConvertToRISCV.cpp, runtime/cmake/quidditch_module.cmake, runtime/samples/nsnet2/CMakeLists.txt, runtime/samples/nsnet2/nsnet2_util.c, runtime/samples/nsnet2/nsnet2_util.h, runtime/samples/vec_multiply/CMakeLists.txt
These variants represent different interesting combinations for evaluation and represent every combination of using xDSL + single or multi-threaded
=> [samples] create multiple variants of NsNet2

codegen/compiler/src/Quidditch/CMakeLists.txt, codegen/compiler/src/Quidditch/LinkExecutables.cpp, codegen/compiler/src/Quidditch/OutlineLinalgOpsToxDSL.cpp, codegen/compiler/src/Quidditch/Passes.td, codegen/compiler/src/Quidditch/QuidditchTarget.cpp, codegen/compiler/src/Quidditch/ReluToMax.cpp
The latter xDSL is capable of lowering to floating point instructions that can be placed inside a `frep` and is therefore a lot faster.
As a side-effect two more kernels in NsNet2 can be compiled which showed an issue with `hal.executable.condition` in the linker that had to be fixed as well.
=> [compiler] Add pattern to raise ReLUs in select to `arith.maximumf` form

codegen/compiler/src/Quidditch/Conversion/ConvertToRISCV.cpp, codegen/compiler/src/Quidditch/Dialect/Snitch/QuidditchSnitchOps.cpp, codegen/compiler/src/Quidditch/Dialect/Snitch/QuidditchSnitchOps.h, codegen/compiler/src/Quidditch/Dialect/Snitch/QuidditchSnitchOps.td, codegen/compiler/src/Quidditch/Target/OutlineLinalgOpsToxDSL.cpp, codegen/compiler/src/Quidditch/Target/QuidditchTarget.cpp, codegen/tests/Dialect/Snitch/bufferization.mlir, codegen/tests/Dialect/Snitch/roundtrip.mlir, codegen/tools/quidditch-opt.cpp
By making it possible to bufferize the operations we are able to form our micro kernels earlier in the pass pipeline prior to bufferization. This is required for other transformation passes such as explicit tensor promotion to L1 memory and subgroup distribution that we are planning to add later.
As a consequence of this change the existing `xdsl_kernel` (now renamed to just `microkernel`) had to be split into two operations, one operating on tensors, the other on memrefs. The reason for this is that the memref version should be isolated from above while the tensor version cannot be for bufferization purposes. The bufferization process itself now converts between the two.
=> [quidditch_snitch] Implement bufferization for microkernels

codegen/compiler/src/Quidditch/Dialect/Snitch/QuidditchSnitchOps.cpp, codegen/compiler/src/Quidditch/Dialect/Snitch/QuidditchSnitchOps.td, codegen/tests/Dialect/Snitch/canonicalization.mlir, codegen/tools/quidditch-opt.cpp
These canonicalizations help to get the microkernel into a minimal form to microoptimize the xDSL generation and also avoid hitting code generation limits. They mostly remove redundant arguments and results.
=> [quidditch_snitch] Implement canonicalization for memref microkernels

codegen/compiler/src/Quidditch/Conversion/CMakeLists.txt, codegen/compiler/src/Quidditch/Conversion/ConvertSnitchToLLVM.cpp, codegen/compiler/src/Quidditch/Conversion/Passes.td, codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchOps.td, codegen/compiler/src/Quidditch/Target/CMakeLists.txt, codegen/compiler/src/Quidditch/Target/QuidditchTarget.cpp, codegen/tests/Conversion/ConvertSnitchToLLVM/l1_memory_view.mlir, codegen/tools/CMakeLists.txt, codegen/tools/quidditch-opt.cpp
This operation is used to represent L1 memory as one single large i8 memref. Allocation within L1 is then simply a `memref.view` into this memref. This PR also implements lowering it to LLVM.
Note that the operation always returns the same memref descriptor, i.e. the memref being returned aliases all other memrefs returned by the operation.
=> [quidditch_snitch] Add `l1_memory_view` op

codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchAttrs.td, codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchOps.cpp, codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchOps.td, codegen/compiler/src/Quidditch/Dialect/Snitch/Transforms/CMakeLists.txt, codegen/compiler/src/Quidditch/Dialect/Snitch/Transforms/Passes.td, codegen/compiler/src/Quidditch/Dialect/Snitch/Transforms/PromoteToL1.cpp, codegen/compiler/src/Quidditch/Target/QuidditchTarget.cpp, codegen/tests/Dialect/Snitch/IR/bufferization.mlir, codegen/tests/Dialect/Snitch/Transforms/promote-to-l1.mlir, runtime/samples/nsnet2/nsnet2_util.c, runtime/samples/util/run_model.c, runtime/samples/util/run_model.h, runtime/samples/vec_multiply/main.c
An invariant of our microkernels is that tensors MUST be in L1 memory or the execution will crash. This PR implements enforces this by adding and creating a new operation called `copy_l1_tensor` which is capable of transferring either from or to L1. During bufferization a copy is performed, if necessary, otherwise the operation is a noop. The `L1EncodingAttr` is used as memory space for L1 MemRefs during bufferization whose lowerings have been implemented in previous PRs.
With this PR it is now also possible to run kernels with buffers allocated in L3/DRAM as long as the used memory fits into L1.
=> [quidditch_snitch] Implement tensor promotion to L1

codegen/compiler/src/Quidditch/Dialect/Snitch/Transforms/PromoteToL1.cpp, codegen/tests/Dialect/Snitch/Transforms/promote-to-l1.mlir
Whether the buffer should be copied and where it should be copied to should be decided by the consumer of the tensor, not the promotion logic. The bufferization framework actually does this for us and does so without introducing spurious copies as the current implementation would.
=> [PromoteToL1] Don't copy buffer back into L3

codegen/compiler/src/Quidditch/Target/CMakeLists.txt, codegen/compiler/src/Quidditch/Target/LibraryBuilder.cpp, codegen/compiler/src/Quidditch/Target/LibraryBuilder.h, codegen/compiler/src/Quidditch/Target/QuidditchTarget.cpp
We want to change the format used to represent an executable. This commit does nothing but fork it to have later diffs show the difference.
=> [compiler] Fork `LibraryBuilder` from `LLVMCPU`

runtime/runtime/src/Quidditch/executable/executable_library.c, runtime/runtime/src/Quidditch/executable/executable_library.h
Forking ahead of changes to the format and for a clearer diff afterwards
=> [runtime] Fork `executable_library`

codegen/compiler/src/Quidditch/Target/LibraryBuilder.cpp, codegen/compiler/src/Quidditch/Target/LibraryBuilder.h, codegen/compiler/src/Quidditch/Target/QuidditchTarget.cpp, runtime/runtime/src/Quidditch/dispatch/dispatch.c, runtime/runtime/src/Quidditch/executable/CMakeLists.txt, runtime/runtime/src/Quidditch/executable/executable.c, runtime/runtime/src/Quidditch/executable/executable.h, runtime/runtime/src/Quidditch/executable/executable_library.h
Once dma core code starts to be generated, we'll be required to find and call the code using the DMA core. While not implemented yet, we already use the field to distinguish between kernels generated by LLVM and xDSL to perform the different workgroup and subgroup distributions.
=> [compiler][runtime] Add DMA core pointer to executable format

runtime/runtime/src/Quidditch/executable/executable.c
This is mostly useful to properly error if we accidentally made an external HAL call that we did not intend to during code generation. That way we emit a proper error.
=> [runtime] Provide import thunks

codegen/compiler/src/Quidditch/Conversion/ConvertSnitchToLLVM.cpp, codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchOps.td, codegen/tests/Conversion/ConvertSnitchToLLVM/barrier.mlir
This operation is used to sync up all cores within a cluster effiecently. We mostly want to use it in DMA and compute core codegen to communicate phases being done which are usually compute and copy phases
=> [quidditch_snitch] Implement barrier operation

codegen/compiler/src/Quidditch/Conversion/ConvertSnitchToLLVM.cpp, codegen/compiler/src/Quidditch/Dialect/Snitch/IR/CMakeLists.txt, codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchDialect.cpp, codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchDialect.td, codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchOps.h, codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchOps.td, codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchTypes.cpp, codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchTypes.h, codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchTypes.td, codegen/tests/Conversion/ConvertSnitchToLLVM/dma_transfer_1d.mlir, codegen/tests/Conversion/ConvertSnitchToLLVM/dma_wait.mlir
This PR implements DMA copy and wait operations. Snitch's DMA is asnychronous and has special hardware support for faster transfers between L1 and L3 than doing it manually. The currentl lowering to LLVM simple performs calls into the snitch runtime for convenience with the idea of these being later inlined via LTO once implemented.
Noteworthy is that the support for various memref shapes, strides and dimension is currently very limited but enough for what IREE generates.
=> [quidditch_snitch] Basic implementations of DMA operations

codegen/compiler/src/Quidditch/Conversion/ConvertSnitchToLLVM.cpp, codegen/tests/Conversion/ConvertSnitchToLLVM/dma_transfer_1d.mlir
Contiguous MemRefs can be copied using just `snrt_dma_start_1d` which simplifies some of the required setup for the DMA. This PR properly implements the detection of such contiguous MemRefs by first checking for an identity layout and otherwise, checking if the sided layout describes an identity layout in all but offset.
=> [SnitchToLLVM] Properly detect contiguous MemRefs

codegen/compiler/src/Quidditch/Conversion/ConvertSnitchToLLVM.cpp, codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchDialect.td, codegen/compiler/src/Quidditch/Dialect/Snitch/Transforms/CMakeLists.txt, codegen/compiler/src/Quidditch/Dialect/Snitch/Transforms/Passes.td, codegen/compiler/src/Quidditch/Dialect/Snitch/Transforms/SpecializeDMACode.cpp, codegen/compiler/src/Quidditch/Target/QuidditchTarget.cpp, codegen/tests/Conversion/ConvertSnitchToLLVM/dma_transfer_1d.mlir, runtime/runtime/src/Quidditch/dispatch/dispatch.c, runtime/runtime/src/Quidditch/dispatch/dispatch.h, runtime/runtime/src/Quidditch/executable/executable.c
Up until now we've been performing memory copies on the compute cores using `memref.copy` which is very slow. This PR instead starts making use of the DMA cores DMA hardware to perform any copying from L1 to L3. As only the DMA core can execute these instructions and only the compute core can execute kernels, this PR also implements a "dma code specialization" pass which copies the original compute core containing DMA instructions, removes all compute instructions from the copy, and inserts required synchronization between the compute and DMA functions.
=> [compiler] Implement DMA code specialization

codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchOps.cpp, codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchOps.td, codegen/compiler/src/Quidditch/Dialect/Snitch/Transforms/PromoteToL1.cpp, codegen/tests/Dialect/Snitch/IR/bufferization.mlir, codegen/tests/Dialect/Snitch/IR/canonicalization.mlir, codegen/tests/Dialect/Snitch/IR/roundtrip.mlir, codegen/tests/Dialect/Snitch/Transforms/promote-to-l1.mlir
There is no fundamental reasons why it only allowed static shapes. While touching the op, also rename it to `copy_tensor` and simplify its bufferization logic a bit. Should be NFC.
Note that bufferization of dynamic dim tensors is not yet implemented and require more changes
=> [quidditch_snitch] Allow dynamic dims in and simplify `copy_l1_tensor`

codegen/compiler/src/Quidditch/Target/FormMicrokernels.cpp, codegen/compiler/src/Quidditch/Target/LinkExecutables.cpp, codegen/compiler/src/Quidditch/Target/QuidditchTarget.cpp
`hal.executable.export` has the (reasonable) invariant of the symbol that is being exported referring to the function that serves as the kernel entry point. We previously broke this invariant by renaming the entrypoint. This PR moves the renaming to very late in the pipeline in LLVM IR to uphold the invariant while in MLIR. A side-effect of this change is that we completely stop depending on the name of the function having any significance on semantics.
=> [compiler] Satisfy invariant of `hal.executable.export`

CMakeLists.txt, runtime/tests/CMakeLists.txt
The default test of the megabuild will only run the precommit tests while the explicit `test-nightly` target can be run to to run the slower tests (currently just NsNet2 variants).
=> [runtime] Add test labels for slow (nightly) and fast (precommit) tests

codegen/compiler/src/Quidditch/Conversion/ConvertToRISCV.cpp
This caused a 20% performance regression in NsNet2
=> [ConvertToRISCV] Fix performance regression due to missing `fmadd`

runtime/samples/nsnet2/nsnet2_util.c
Allocating a 161 * 8 array on the stack takes away most of our cores stack memory, which is less than ideal.
=> [runtime][samples] Reduce stack usage

codegen/compiler/src/Quidditch/Conversion/ConvertSnitchToLLVM.cpp, codegen/compiler/src/Quidditch/Conversion/ConvertToRISCV.cpp, codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchOps.cpp, codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchOps.td, codegen/tests/Conversion/ConvertSnitchToLLVM/microkernel_call.mlir
The op serves two purposes:
* Representing xDSL compiled RISC-V output in our IR that must be called later
* Implementing the custom calling convention that we implement with xDSL kernels
In particular, we always pass the buffer pointer to xDSL, not the aligned pointer.
=> [quidditch_snitch] Add `call_microkernel` op

codegen/compiler/src/Quidditch/Conversion/ConvertSnitchToLLVM.cpp, codegen/compiler/src/Quidditch/Conversion/ConvertToRISCV.cpp
Since we always pass the offset pointer, having xDSL also apply an offset is incorrect. Similarly, we want to pretend that there is no offset when a dynamic offset is present.
=> [ConvertToRISCV] Do not provide MemRef offset to xDSL

codegen/compiler/src/Quidditch/Target/CMakeLists.txt, codegen/compiler/src/Quidditch/Target/ConfigureForSnitch.cpp, codegen/compiler/src/Quidditch/Target/Passes.h, codegen/compiler/src/Quidditch/Target/Passes.td, codegen/compiler/src/Quidditch/Target/QuidditchTarget.cpp, codegen/compiler/src/Quidditch/Target/TensorTile.cpp
Both levels of tiling are cruical optimizations for accelerating the NN execution on snitch. Reduction tiling allows us to make larger workgroups and increase parallism for the later thread tiling. Thread tiling is required to distribute a linalg operations accross all 8 compute cores.
The former materialzies as a `scf.for` while the latter to an `scf.forall`. To make this PR smaller, the `scf.forall` is lowered to just an `scf.for` with later PRs implementing the distribution of `scf.forall`s.
=> [compiler] Implement Reduction and Thread tiling

codegen/compiler/src/Quidditch/Conversion/ConvertSnitchToLLVM.cpp, codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchOps.td, codegen/compiler/src/Quidditch/Dialect/Snitch/Transforms/CMakeLists.txt, codegen/compiler/src/Quidditch/Dialect/Snitch/Transforms/LowerForallOp.cpp, codegen/compiler/src/Quidditch/Dialect/Snitch/Transforms/Passes.td, codegen/compiler/src/Quidditch/Target/QuidditchTarget.cpp, codegen/tests/Conversion/ConvertSnitchToLLVM/cluster_index.mlir, codegen/tests/Dialect/Snitch/Transforms/lower-forall.mlir, runtime/runtime/src/Quidditch/dispatch/dispatch.c, runtime/runtime/src/Quidditch/dispatch/dispatch.h, runtime/runtime/src/Quidditch/executable/executable.c
A previous PR implemented tiling of parallel dimensions to `scf.forall` but did not yet implement the lowering of `scf.forall`. This PR implements the lowering of `scf.forall` and distributing it to every compute core. This is achieved using the `quidditch_snitch` op which returns an id of 0 to `compute_cores - 1`. We then lower the `scf.forall` to an `scf.for` where each compute core takes an `1/compute_cores` slice of the iteration space.
=> [compiler][runtime] Implement distributing `forall` to all compute cores

codegen/compiler/src/Quidditch/Dialect/Snitch/Transforms/CMakeLists.txt, codegen/compiler/src/Quidditch/Dialect/Snitch/Transforms/LowerForallOp.cpp, codegen/compiler/src/Quidditch/Dialect/Snitch/Transforms/Passes.td, codegen/compiler/src/Quidditch/Target/CMakeLists.txt, codegen/compiler/src/Quidditch/Target/Passes.td, codegen/compiler/src/Quidditch/Target/QuidditchTarget.cpp, codegen/compiler/src/Quidditch/Target/RemoveTrivialLoops.cpp, codegen/tests/Dialect/Snitch/Transforms/lower-forall.mlir, codegen/tests/Target/remove-trivial-loops.mlir
This is mostly a port of the same pass from IREE but specializing for our `cluster_index` operation and its range.
=> [compiler] Add `remove-trivial-loops` pass for dead `scf.for`s

runtime/tests/CMakeLists.txt, runtime/util/snitch_trace_to_perfetto.py
Using a few state machines and some knowledge about Snitch we can reconstruct metrics such as time spent streaming, time spent in a barrier and DMA transfers performed by processing the traces.
Using this information we can see where time is actually spent in a kernel (memory transfers vs compute etc.).
=> [util] Add Streaming, Barriers and DMAs to traces

CMakeLists.txt
Marking them as such causes cmake to reconfigure and rerun `pip install` if any of these files changed. Most importantly, it also triggers if the `xDSL` version we use changes, making it impossible to accidentally test and use an xDSL installation different from the one checked out as a submodule.
=> [cmake] Mark python requirements 'CONFIGURE_DEPENDS'

codegen/compiler/src/Quidditch/Conversion/ConvertSnitchToLLVM.cpp, codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchOps.td, codegen/compiler/src/Quidditch/Dialect/Snitch/Transforms/SpecializeDMACode.cpp, codegen/tests/Conversion/ConvertSnitchToLLVM/microkernel_fence.mlir, codegen/tests/Dialect/Snitch/Transforms/specialize-dma-code.mlir
Since the introduction of reduction tiling, we've introduced errors in the kernel code through the introduction of race conditions. We incorrectly assumed that `barrier` ops serve as synchronization points for the FPU and the integer core, but this is not the case. This resulted in scenarios such as the DMA copying an L1 buffer back to DRAM despite the calculation not having finished or (in the reduction tiling case) the DMA overriding an L1 buffer that is still in use.
The new `microkernel_fence` op ensures the FPU (and therefore the microkernel invocations) are in sync with the integer core. The specialization pass conservatively places the op before `start_dma_transfer` operations, similar to the barrier.
This will hurt performance compared to the numbers we've previously been getting, …
=> [quidditch_snitch] Introduce and use `microkernel_fence` op

codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchOps.cpp, codegen/tests/Dialect/Snitch/IR/bufferization.mlir
Even if our compilation pipeline currently has bad support for dynamic dimensions (as xDSL straight up does not support them), supporting them as much as possible gives us more flexible as to when and where to get rid of them + allowing more experimentation with different kinds of tiling.
=> [quidditch_snitch] Implement `copy_tensor` bufferization of dynamic dims

codegen/compiler/src/Quidditch/Dialect/Snitch/IR/CMakeLists.txt, codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchAttrs.cpp, codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchAttrs.h, codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchAttrs.td, codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchDialect.cpp, codegen/compiler/src/Quidditch/Target/ConfigureForSnitch.cpp, codegen/compiler/src/Quidditch/Target/TensorTile.cpp
This op replaces the use of IREE's default `LoweringConfigAttr` with our own to give us a more structured and nicer to use attribute for defining our lowering parameters.
=> [quidditch_snitch][NFC] Add `LoweringConfigAttr`

codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchOps.cpp, codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchOps.td, codegen/compiler/src/Quidditch/Dialect/Snitch/Transforms/PromoteToL1.cpp, codegen/tests/Dialect/Snitch/IR/canonicalization.mlir
The copy to L3 memory branch was dead code since we never need to explicitly make sure that a tensor is in L3. Copies from L3 back to L1 are inserted implicitly by the bufferization framework and need (and should) not be modelled using the operation.
=> [quidditch_snitch] Simplify `copy_tensor`

codegen/compiler/src/Quidditch/Conversion/ConvertSnitchToLLVM.cpp, codegen/tests/Conversion/ConvertSnitchToLLVM/dma_transfer.mlir
They were accidentally in element type unit, which the DMA does not like nor understand.
We are now back to bit equality with LLVM
=> [ConvertSnitchToLLVM] Make sure DMA strides are in bytes

codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchAttrs.cpp, codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchAttrs.td, codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchDialect.cpp, codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchOps.td, codegen/compiler/src/Quidditch/Target/ConfigureForSnitch.cpp, codegen/compiler/src/Quidditch/Target/Passes.h, codegen/compiler/src/Quidditch/Target/QuidditchTarget.cpp, codegen/compiler/src/Quidditch/Target/TensorTile.cpp
Previously, workgroup tiling was responsible for two things:
* Making sure the working set fits into L1 memory and
* Splitting into workgroups for distribution
However, this is undesirable as this forces us to choose a tile size satisfying both requirements. Instead, this PR adds a new level of tiling called L1 tiling which takes over the responsibility of making the working set fit into L1 memory. Workgroup distribution tiling is now solely responsible for workgroup concurrency. As we are currently compiling for just one snitch cluster, the existing tile sizes have been changed to L1 tile sizes except the reduction dimension. The reduction dimension tiling should come prior to L1 tiling, which happens to be the case right now. Larger workgroups are desirable in the absence of concurrency …
=> [TensorTile] Add dedicated L1 tiling

codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchOps.cpp, codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchOps.td, codegen/compiler/src/Quidditch/Dialect/Snitch/Transforms/PromoteToL1.cpp, codegen/tests/Dialect/Snitch/IR/bufferization.mlir, codegen/tests/Dialect/Snitch/IR/canonicalization.mlir, codegen/tests/Dialect/Snitch/IR/roundtrip.mlir, codegen/tests/Dialect/Snitch/Transforms/promote-operands-to-l1.mlir, test.mlir
The current tensor copy is fully synchronous that prevents us from doing transfer optimization utilizing the asynchronous nature of the DMA. While these could be done on MemRefs, having them operate on tensors preserves the use-def chain and allows us not to care about aliasing.
=> [quidditch_snitch] Introduce asynchronous tensor copy ops

codegen/compiler/src/Quidditch/Conversion/ConvertSnitchToLLVM.cpp, codegen/tests/Conversion/ConvertSnitchToLLVM/dma_wait.mlir
Up until now all `wait_for_dma_transfers` ops did not only wait for the transfers denoted by the tokens to be completed, but all transfers within the DMA. This blocks implementing transformations such as pipelining and is generally very unoptimized.
=> [ConvertSnitchToLLVM] Implement single token wait

codegen/compiler/src/Quidditch/Target/CMakeLists.txt, codegen/compiler/src/Quidditch/Target/ConvertToLLVM.cpp, codegen/compiler/src/Quidditch/Target/Passes.td, codegen/compiler/src/Quidditch/Target/QuidditchTarget.cpp
Any patterns involving type system changes need to be run in one large dialect conversion. Our existing `ConvertSnitchToLLVM` pass has so far worked as it did not interact with other dialects operations but is nevertheless strongly limited.
This PR therefore does the initial step of forking the `ConvertToLLVM` pass from IREE's LLVMCPU backend. Only the bare minimum of changes for integration are performed to have a clean diff of Quidditch specific changes in follow up PRs.
This additionally creates exciting opportunities in the future regarding a more optimized ABI for Snitch and Occamy.
=> [Target] Fork LLVMCPU's `ConvertToLLVM` pass

codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchOps.cpp, codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchOps.h, codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchOps.td, codegen/tests/Dialect/Snitch/IR/bufferization.mlir, codegen/tests/Dialect/Snitch/IR/canonicalization.mlir
This op is used to generically represent a pipelined `for` loop consisting of multiple stages where different loop iterations may be executing concurrently. Our use-case first and foremost being the implementation of dual buffering which effectively is separating the copying and the computation into different pipeline stages
=> [quidditch_snitch] Introduce `pipeline` op

codegen/compiler/src/Quidditch/Dialect/Snitch/Transforms/CMakeLists.txt, codegen/compiler/src/Quidditch/Dialect/Snitch/Transforms/LowerPipelineOp.cpp, codegen/compiler/src/Quidditch/Dialect/Snitch/Transforms/Passes.td, codegen/tests/Dialect/Snitch/Transforms/lower-pipeline.mlir
This PR implements the lowering of bufferized `pipeline` operations to standard set of dialects. The lowering itself does not introduce any concurrency but rather relies on the stages to start and wait for concurrent operations.
It starts of by generating a "ramp up", which pastes all stages after each other until the last stage could start executing. It then enters the hot loop which is a single `scf.for` that executes every pipeline stage after another, albeit with a different IV for each. After the core `scf.for` a ramp down makes sure that later stages consume the results of the previous stages that were still executed within the `scf.for`.
The only limitation of the lowering is that it currently requires the loop to execute at least "numStages - 1" many times. Otherwise, UB occurs.
=> [quidditch_snitch] Implement lowering of `pipeline` op

codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchAttrs.td, codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchDialect.cpp, codegen/compiler/src/Quidditch/Dialect/Snitch/Transforms/CMakeLists.txt, codegen/compiler/src/Quidditch/Dialect/Snitch/Transforms/Passes.td, codegen/compiler/src/Quidditch/Dialect/Snitch/Transforms/PipelineCopyCompute.cpp, codegen/compiler/src/Quidditch/Target/ConfigureForSnitch.cpp, codegen/compiler/src/Quidditch/Target/QuidditchTarget.cpp, codegen/tests/Dialect/Snitch/Transforms/pipeline-copy-compute.mlir
This PR implements the lifting of `scf.for` ops containing a compute op + tensor copy ops into a `pipeline` op where copy and compute operations are split into two pipeline stages. An additional `dual_buffer` attribute on the lowering config of the compute op controls whether this should be performed (which it almost should be). This also updates our configs and pipeline to perform dual buffering of the rows of the matrix.
=> [quidditch_snitch] Implement `pipeline-copy-compute` pass

codegen/compiler/src/Quidditch/Dialect/Snitch/Transforms/LowerL1Allocations.cpp, codegen/tests/Dialect/Snitch/Transforms/lower-l1-allocations.mlir
The previous lowering would crash in this case as `memref.view` op does not support a non-identity result `memref`. This PR fixes the lowering by first creating a `view` into a buffer with enough elements to support a given layout (i.e. includes padding) before `reinterpret_cast`ing to the original layout of the `alloca`.
=> [LowerL1Allocations] Support non-identity strides in L1 `memref.alloca`

runtime/samples/nsnet2/nsnet2_util.c, runtime/samples/util/run_model.c, runtime/samples/util/run_model.h, runtime/samples/vec_multiply/main.c
This avoids allocating and then copying the input data. Mostly useful in short running tests where the VM overhead dominates.
=> [samples] Speed up simulation by importing buffers

codegen/compiler/src/Quidditch/Conversion/ConvertSnitchToLLVM.cpp, codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchOps.td, codegen/compiler/src/Quidditch/Dialect/Snitch/Transforms/LowerForallOp.cpp, codegen/compiler/src/Quidditch/Target/RemoveTrivialLoops.cpp, codegen/tests/Conversion/ConvertSnitchToLLVM/compute_core_index.mlir, codegen/tests/Dialect/Snitch/Transforms/lower-forall.mlir, codegen/tests/Target/remove-trivial-loops.mlir
The op as it is currently used and specified returns the index of compute cores (in our current simulations 0 to exclusive 8) and has unspecified behavior on the DMA core. This will be used in a later PR to properly lower it when doing DMA code specialization.
=> [quidditch_snitch] Rename `cluster_index` to `compute_core_index`

codegen/compiler/src/Quidditch/Conversion/ConvertSnitchToLLVM.cpp, codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchOps.td, codegen/compiler/src/Quidditch/Dialect/Snitch/Transforms/LowerForallOp.cpp, codegen/compiler/src/Quidditch/Dialect/Snitch/Transforms/SpecializeDMACode.cpp, codegen/compiler/src/Quidditch/Target/RemoveTrivialLoops.cpp, codegen/tests/Conversion/ConvertSnitchToLLVM/compute_core_index.mlir, codegen/tests/Dialect/Snitch/Transforms/lower-forall.mlir, codegen/tests/Dialect/Snitch/Transforms/specialize-dma-code.mlir, codegen/tests/Target/remove-trivial-loops.mlir
Barriers may be inserted in a loop resulting from the lowering of a `scf.forall`. The lowering of `compute_core_index` unfortunately returns `num_compute_cores + 1` which is outside the specified range of the operation and leads to such loops and their barriers being skipped by the DMA core. As the pass already assumes non-divergent control flow, we can fix this by specializing `compute_core_index` to any integer in the defined range of the op.
=> [SpecializeDMACode] Properly lower `compute_core_index`

codegen/compiler/src/Quidditch/Conversion/ConvertToRISCV.cpp
While we are not able to leverage snitch's SSR and FREP extension if `xdsl-opt` fails, our schedule and use of L1 memory should generally lead to performance improvements over the LLVM backend's kernel. This PR therefore changes the mechanism when `xdsl-opt` fails to inline the linalg operation and erase the `quidditch_snitch.memref.microkernel`, instead of the current behavior of discarding the kernel entirely.
=> [ConvertToRISCV] Fallback to Linalg lowering if `xdsl-opt` fails

codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchAttrs.td, codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchDialect.cpp, codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchDialect.td, codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchOps.cpp, codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchOps.td, codegen/tests/Dialect/Snitch/IR/canonicalization.mlir
This is the attribute version corresponding to the `completed_token` operation. The latter is now a `ConstantLike` that folds to this token value.
The main advantage is the more comfortable use of the `fold` API rather than canonicalization patterns.
=> [quidditch_snitch] Add `CompletedTokenAttr`

codegen/compiler/src/Quidditch/Conversion/ConvertSnitchToLLVM.cpp, codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchOps.cpp, codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchOps.td, codegen/compiler/src/Quidditch/Target/Passes.td, codegen/tests/Conversion/ConvertSnitchToLLVM/zero_mem_transfer.mlir
This operation is a special kind of DMA transfer leveraging both Snitch's DMA and a special address space in the cluster's memory that always returns 0. This allows zeroing memory in bursts of 64kB using the DMA.
While currently unused in the pipeline, the operation will be used soon to implement a lowering of `tensor.pad`. Occurrences of `linalg.fill` with zero can also be optimized in the future.
=> [quidditch_snitch] Add `start_zero_mem_transfer` operation

codegen/compiler/src/Quidditch/Dialect/Snitch/IR/CMakeLists.txt, codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchInterfaces.cpp, codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchInterfaces.h, codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchInterfaces.td, codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchOps.cpp, codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchOps.h, codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchOps.td, codegen/compiler/src/Quidditch/Dialect/Snitch/Transforms/SpecializeDMACode.cpp
The code previously used the classic "switch over operations" approach to specilization. This causes code implementing the "behavior" of the operation to be non-local to the operation implementation but in the pass instead. This also makes adding future operations easier.
=> [quidditch_snitch] Simplify `specialize-dma-code` using interfaces

codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchOps.cpp, codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchOps.td, codegen/tests/Dialect/Snitch/IR/bufferization.mlir, codegen/tests/Dialect/Snitch/IR/canonicalization.mlir, codegen/tests/Dialect/Snitch/IR/roundtrip.mlir, codegen/tests/Dialect/Snitch/Transforms/pipeline-copy-compute.mlir, codegen/tests/Dialect/Snitch/Transforms/promote-operands-to-l1.mlir
We occasionally encounter shapes that are challenging to tile due to their prime factors involved. Attempting to distribute these (e.g. to compute cores or vector lanes) when the number of required tiles is not a factor of the dimension leads to generating dynamic dimensions which the microkernel compilation is unable to deal with. Similarly, once we are on `f32`, we are required to vectorize the kernel and have a restriction that the tile size of e.g. a matvec is a multiple of 4, 8 etc.
This PR therefore introduces optional padding to the `start_dma_transfer` op that can be added at the end of each tensor dimension. When tiled, the padding can be chosen to guarantee that a tensor is always of a given static shape, solving the issue noted above. For now, the value used for padding is …
=> [quidditch_snitch] Add padding capabilities to `start_tensor_copy`

codegen/compiler/src/Quidditch/Dialect/Snitch/Transforms/PromoteToL1.cpp, codegen/tests/Dialect/Snitch/Transforms/promote-operands-to-l1.mlir
The pass would previously create invalid IR by always replacing a tensor value with the promoted tensor despite its insertion point being before a compute operation. If another operation before the compute operation would have a use of the tensor it'd get replaced despite being illegal.
The fix is to simply not replace the value of the tensor but rather the operand use. CSE should clean up any redundancy.
=> [PromoteToL1] Fix dominance bug

codegen/compiler/src/Quidditch/Target/CMakeLists.txt, codegen/compiler/src/Quidditch/Target/PadToTilingConfig.cpp, codegen/compiler/src/Quidditch/Target/Passes.td, codegen/compiler/src/Quidditch/Target/QuidditchTarget.cpp, codegen/tests/Target/pad-to-tiling-config.mlir
In the future we will have scenarios requiring padding to be inserted to be able to effectively tile and vectorize operations.
This pass implements the logic required to insert and optimize `tensor.pad` operations to pad operands of linalg operations to a multiple of a given number. The current logic only does so for tile sizes.
Optimization wise, the pass optimizes zero-padding to undef-padding where possible and attempts to fuse them into various operations when possible.
A future pass will lower `tensor.pad` to DMA transfers to fully integrate it into compilation flow.
=> [Target] Implement pass inserting `tensor.pad` if required

codegen/compiler/src/Quidditch/Dialect/Snitch/Transforms/Passes.td, codegen/compiler/src/Quidditch/Dialect/Snitch/Transforms/PromoteToL1.cpp, codegen/compiler/src/Quidditch/Target/ConfigureForSnitch.cpp, codegen/compiler/src/Quidditch/Target/QuidditchTarget.cpp, codegen/tests/Dialect/Snitch/Transforms/promote-pads-to-l1.mlir
`tensor.pad`, as we produce them, can be lowered to `start_tensor_copy`. The latter will perform the L1 allocation and copy operations during bufferization.
The one not-nice part of the pass is that it does so indiscriminately for all `tensor.pad` operations. I am very unsure about whether there are any guarantees by IREE that'd never encounter `tensor.pad` operations in kernels.
This was also the last pass required to compile the last kernel in NsNet2
=> [PromotePadsToL1] Implement pass lowering `tensor.pad`

codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchOps.cpp, codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchOps.td, codegen/compiler/src/Quidditch/Dialect/Snitch/Transforms/PromoteToL1.cpp, codegen/tests/Dialect/Snitch/IR/bufferization.mlir, codegen/tests/Dialect/Snitch/Transforms/promote-pads-to-l1.mlir
Undef padding was previously lowered to zero paddings, which involve additional DMA transfers required to zero out an allocation. The majority of operations do not require padding with a specific value making the zero padding and therefore the DMA transfers redundant.
=> [quidditch_snitch] Implement undef padding for `start_tensor_copy`

codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchOps.cpp, codegen/tests/Dialect/Snitch/IR/canonicalization.mlir
The folder logic was too conservative and would not elide a tensor copy if the tensor it was transferring was padded. The intended logic was to not elide the copy if the copy itself is padded unless the padding matches the tensor being transferred.
=> [quidditch_snitch] Remove redundant `start_tensor_copy` op in more cases

codegen/compiler/src/Quidditch/Conversion/ConvertSnitchToLLVM.cpp, codegen/tests/Conversion/ConvertSnitchToLLVM/dma_transfer.mlir
Dynamic memrefs were miscompiled as the wrong index was used to read the size of a dynamic dimension.
=> [ConvertSnitchToLLVM] Fix bug in 1d size calculation

codegen/compiler/src/Quidditch/Conversion/ConvertSnitchToLLVM.cpp, codegen/tests/Conversion/ConvertSnitchToLLVM/dma_transfer.mlir
The previous logic was too overly complicated and had false negatives. Previous PRs that implemented zero-mem transfer added nice helpers that are now used to detect the common contiguous dimensions between a source and destination MemRef.
=> [ConvertSnitchToLLVM] Improve DMA transfers contiguity check

codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchAttrs.td, codegen/compiler/src/Quidditch/Dialect/Snitch/IR/QuidditchSnitchDialect.cpp, codegen/compiler/src/Quidditch/Target/ConfigureForSnitch.cpp, codegen/compiler/src/Quidditch/Target/Passes.h, codegen/compiler/src/Quidditch/Target/Passes.td, codegen/compiler/src/Quidditch/Target/QuidditchTarget.cpp, codegen/compiler/src/Quidditch/Target/TensorTile.cpp
Conceptually, reduction tiling achieves the same goal as L1 tiling: Both ensure that the output tile is in L1 memory. The main reason why this used to be an extra step nevertheless is the performance requirement of tiling reduction prior to any of the parallel dimensions in a matvec to reduce memory transfers. By adding a loop interchange configuration (which could in practice also be hard-coded probably), we can replicate this behavior using only a single tiling config.
=> [TensorTile] Merge reduction tiling into L1 tiling

codegen/compiler/src/Quidditch/Conversion/CMakeLists.txt, codegen/compiler/src/Quidditch/Conversion/ConvertDMAToLLVM.cpp, codegen/compiler/src/Quidditch/Dialect/SnitchDMA/CMakeLists.txt, codegen/compiler/src/Quidditch/Dialect/SnitchDMA/IR/CMakeLists.txt, codegen/compiler/src/Quidditch/Dialect/SnitchDMA/IR/SnitchDMAAttrs.cpp, codegen/compiler/src/Quidditch/Dialect/SnitchDMA/IR/SnitchDMAAttrs.h, codegen/compiler/src/Quidditch/Dialect/SnitchDMA/IR/SnitchDMAAttrs.td, codegen/compiler/src/Quidditch/Dialect/SnitchDMA/IR/SnitchDMADialect.cpp, codegen/compiler/src/Quidditch/Dialect/SnitchDMA/IR/SnitchDMADialect.h, codegen/compiler/src/Quidditch/Dialect/SnitchDMA/IR/SnitchDMADialect.td, codegen/compiler/src/Quidditch/Dialect/SnitchDMA/IR/SnitchDMAOps.cpp, codegen/compiler/src/Quidditch/Dialect/SnitchDMA/IR/SnitchDMAOps.h, codegen/compiler/src/Quidditch/Dialect/SnitchDMA/IR/SnitchDMAOps.td, codegen/compiler/src/Quidditch/Dialect/SnitchDMA/IR/SnitchDMATypes.cpp, codegen/compiler/src/Quidditch/Dialect/SnitchDMA/IR/SnitchDMATypes.h, codegen/compiler/src/Quidditch/Dialect/SnitchDMA/IR/SnitchDMATypes.td, codegen/compiler/src/Quidditch/Target/ConvertToLLVM.cpp, codegen/compiler/src/Quidditch/Target/Passes.td, codegen/compiler/src/Quidditch/Target/QuidditchTarget.cpp, codegen/tools/CMakeLists.txt, codegen/tools/quidditch-opt.cpp
The DMA dialect represents DMA operations in their purest forms: Moving data from one MemRef to another.
The real world is unfortunately not as pretty: Snitch's DMA only supports two-dimensional transfers, the zero region is of a specific size and DMA configuration is relatively expensive.
This PR introduces the `SnitchDMA` dialect which is meant to handle any Snitch specific legalizations but also optimizations.
The intention for the future is to have lowering of DMA operations split into multiple passes and phases performing 1) legalization of DMA transfers, 2) Optimization of configuration, 3) optimization of number of waits and 4) lowering to LLVM.
As a first step, this PR only introduces the dialect and the equivalent of the `dmstati` instruction which is used in the current one-shot …
=> [SnitchDMA] Introduce `SnitchDMA` dialect

codegen/compiler/src/Quidditch/Dialect/DMA/IR/DMAOps.cpp, codegen/compiler/src/Quidditch/Dialect/DMA/IR/DMAOps.td, codegen/tests/Dialect/DMA/IR/bufferization.mlir
The described semantics give more flexibility to the backend and additionally fixes issues we've seen with Snitch's DMA.
=> [DMA] Clarify concurrent behaviour of transfers and fix `start_tensor_copy`

codegen/compiler/src/Quidditch/Conversion/ConvertDMAToLLVM.cpp, codegen/compiler/src/Quidditch/Dialect/DMA/Extensions/DMACoreSpecializationOpInterfaceImpl.cpp, codegen/compiler/src/Quidditch/Dialect/DMA/IR/DMAOps.cpp, codegen/compiler/src/Quidditch/Dialect/DMA/IR/DMAOps.td, codegen/compiler/src/Quidditch/Target/QuidditchTarget.cpp, codegen/tests/Conversion/ConvertDMAToLLVM/combine_tokens.mlir, codegen/tests/Conversion/ConvertDMAToLLVM/dma_wait.mlir, codegen/tests/Dialect/DMA/IR/bufferization.mlir, codegen/tests/Dialect/DMA/IR/canonicalization.mlir, codegen/tests/Dialect/DMA/IR/roundtrip.mlir, codegen/tests/Dialect/Snitch/Transforms/lower-pipeline.mlir, codegen/tests/Dialect/Snitch/Transforms/specialize-dma-code.mlir
Being able to dynamically combine tokens to await a runtime-dependent number of DMA transfers is a requirement for implementing legalization of DMA transfers in the `dma` dialect.
This PR therefore adds the `combined_tokens` op which combines multiple tokens into one. The lowering for Snitch leverages the monotonicity guarantee of IDs to combine them. Note that this only works with a single channel DMA right now.
As this subsumes the multi-token capabilities of `wait_for_transfers`, it has been renamed to just `wait_for_transfer` and only accepts a single token input now.
=> [DMA] Add `combine_token` op

codegen/compiler/src/Quidditch/Conversion/ConvertDMAToLLVM.cpp, codegen/compiler/src/Quidditch/Dialect/SnitchDMA/Transforms/CMakeLists.txt, codegen/compiler/src/Quidditch/Dialect/SnitchDMA/Transforms/LegalizeDMAOperations.cpp, codegen/compiler/src/Quidditch/Dialect/SnitchDMA/Transforms/Passes.h, codegen/compiler/src/Quidditch/Dialect/SnitchDMA/Transforms/Passes.td, codegen/compiler/src/Quidditch/Target/CMakeLists.txt, codegen/compiler/src/Quidditch/Target/QuidditchTarget.cpp, codegen/tests/Conversion/ConvertDMAToLLVM/dma_transfer.mlir, codegen/tests/Dialect/SnitchDMA/Transforms/dma_transfer.mlir, codegen/tools/CMakeLists.txt, codegen/tools/quidditch-opt.cpp
It is up to the target, in this case snitch, to dictate which DMA transfers are directly legal or not. This logic previously lived in `DMAToLLVM` and due to being part of the "one-shot-to-llvm" pass, difficult to test and implement.
This PR therefore splits the logic into a dedicated legalization pass with the lowering to LLVM greatly simplified.
=> [SnitchDMA] Split transfer legalization out of `DMAToLLVM`
